name: C/C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install gcovr
      run: sudo apt-get install -y gcovr
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        run_tests: ON
        config: Debug
        cmake_args: -DCODE_COVERAGE=ON
    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

