name: C/C++ CI

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        configs: [Release, Debug]
        compilers: [g++]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0

#     - name: Install clang-16
#       run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && sudo apt-add-repository "deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy main" && sudo apt-get update && sudo apt-get install clang-16

    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        run_tests: ON
        config: ${{ matrix.configs }}
        cmake_args: -DCMAKE_CXX_COMPILER=${{ matrix.compilers }}
