name: CI

on:
  push

jobs:
  build:
    runs-on: [osx-x64, osx-arm64]
    strategy:
      matrix:
        os: [macos-latest]
        configs: [Release, Debug]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
      
    - name: Test
      run: brew install gcc@11 && which gcc && which g++ && which g++-11

    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        run_tests: OFF
        cmake_args: -DCO_ECS_ENABLE_EXAMPLES=ON
        config: ${{ matrix.configs }}
        
    - name: Run example
      run: uname -a && cd build && make && examples/hello-registry/hello-registry
